
#######################################################################################################
                             PROJECT: keras
#######################################################################################################
CLONING PROJECT:
✓ SUCCESSFUL! This project is already cloned: https://github.com/keras-team/keras
.......................................................................................................
BUGGY LINES:
Suspicious lines to bug1:
1206,1220,1234,2902,2903
Suspicious lines to bug2:

Suspicious lines to bug3:
140,141,142,153,154
Suspicious lines to bug4:
706
Suspicious lines to bug5:
173
Suspicious lines to bug6:
413
Suspicious lines to bug7:
323
Suspicious lines to bug8:
980,983,1029,1031
Suspicious lines to bug9:
120,121
Suspicious lines to bug10:
435,481,482,483,498
Suspicious lines to bug11:
43,44,51,64,66
Suspicious lines to bug12:
The file is empty or does not exist: /Users/daniel/Bachelorarbeit/bugsinpy/projects/keras/bugs/12/bug_patch.txt
Not Found
Suspicious lines to bug13:
127
Suspicious lines to bug14:
48
Suspicious lines to bug15:
1125,1133,1135,1161
Suspicious lines to bug16:
222,223,274,276,281
Suspicious lines to bug17:
37
Suspicious lines to bug18:
2548,2646
Suspicious lines to bug19:
1442,61,74,75,76
Suspicious lines to bug20:
2189,2211,3452,3589,3613
Suspicious lines to bug21:
488
Suspicious lines to bug22:

Suspicious lines to bug23:
152,153
Suspicious lines to bug24:
789,790
Suspicious lines to bug25:

Suspicious lines to bug26:
2874
Suspicious lines to bug27:

Suspicious lines to bug28:
332,344,348
Suspicious lines to bug29:
1177,1178,1179,1366,1367
Suspicious lines to bug30:
2215,2402
Suspicious lines to bug31:
3945,3946
Suspicious lines to bug32:
901,909,918,939,942
Suspicious lines to bug33:
41,42,44,56
Suspicious lines to bug34:
2165,2197,2369,2493
Suspicious lines to bug35:
583,584,1230
Suspicious lines to bug36:
3419,3422
Suspicious lines to bug37:
521,523,527,324,325
Suspicious lines to bug38:
109
Suspicious lines to bug39:
330
Suspicious lines to bug40:
398,400,408
Suspicious lines to bug41:
556,634,639,642,655
Suspicious lines to bug42:
1903,1944,2014,2030,2031
Suspicious lines to bug43:

Suspicious lines to bug44:

Suspicious lines to bug45:
1806,1807,1808,1809
.......................................................................................................

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 1

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 331d5b0102ab0cc79cece1f03cc551d8105db3c9
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/initializers_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [1206, 1220, 1234, 2902, 2903]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 1206
✓
Start transforming line: 1220
✓
Start transforming line: 1234
✓
Start transforming line: 2902
x Fail! Line: 2902 could not be transformed: '   '
Start transforming line: 2903
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 80 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[2902]
✓ Number of created sketches:80
Time needed: 0.04 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 2

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 3

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: c0d1709cbae3d05efc6dd224230012bc120be8e5
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/models.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/test_sequential_model.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/models.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [140, 141, 142, 153, 154]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 140
x Fail! Line: 140 could not be transformed: 'output_masks = to_list('
Start transforming line: 141
x Fail! Line: 141 could not be transformed: 'layer.compute_mask(computed_tensor,'
Start transforming line: 142
x Fail! Line: 142 could not be transformed: '   computed_mask))'
Start transforming line: 153
x Fail! Line: 153 could not be transformed: 'output_masks = to_list('
Start transforming line: 154
x Fail! Line: 154 could not be transformed: 'layer.compute_mask(computed_tensors,'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[140, 141, 142, 153, 154]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 4

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: b0bfd5201da2bfced84028bcc5bda05bdfd75af7
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/optimizers.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/optimizers_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/optimizers.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [706]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 706
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 3 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:3
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 5

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: b847b4601d608050bab6eccd049fce28b7bf1b1f
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/utils/data_utils.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/utils/data_utils_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/utils/data_utils.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [173]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 173
x Fail! Line: 173 could not be transformed: 'cache_dir = os.path.join(os.path.expanduser('~'), '.keras')'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[173]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 6

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 88af7d0c97497b5c3a198ee9416b2accfbc72c36
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training_utils.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/test_loss_masking.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training_utils.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [413]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 413
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 2 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:2
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 7

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 26b620fb37c885d60183f83abc744f43775ce75a
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/wrappers/scikit_learn.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/wrappers/scikit_learn_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/wrappers/scikit_learn.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [323]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 323
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 4 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:4
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 8

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 87540a2a2f42e00c4a2ca7ca35d19f96e62e6cb0
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/network.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/engine/test_topology.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/network.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [980, 983, 1029, 1031]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 980
✓
Start transforming line: 983
x Fail! Line: 983 could not be transformed: 'input_tensors.append('
Start transforming line: 1029
✓
Start transforming line: 1031
x Fail! Line: 1031 could not be transformed: 'name = config.get('name')'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 23 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[983, 1031]
✓ Number of created sketches:23
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 9

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 0cd3b07eb5de1aaaad84d1ff7f7c2ed7dab4b23c
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/docs/autogen.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/test_doc_auto_generation.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/docs/autogen.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [120, 121]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 120
x Fail! Line: 120 could not be transformed: 'block = docstring[starting_point(None ending_point == -1 '
Start transforming line: 121
x Fail! Line: 121 could not be transformed: '  ending_point - 1)]'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[120, 121]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 10

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 8f41e41eda6e8ea96403cae5798a5a89c8bb5605
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training_utils.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/engine/test_training.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training_utils.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [435, 481, 482, 483, 498]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 435
x Fail! Line: 435 could not be transformed: 'weight array.'
Start transforming line: 481
✓
Start transforming line: 482
x Fail! Line: 482 could not be transformed: 'warnings.warn('Found both `sample_weight` and `class_weight` ''
Start transforming line: 483
x Fail! Line: 483 could not be transformed: '  '`class_weight` argument will be ignored.')'
Start transforming line: 498
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 35 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[435, 482, 483]
✓ Number of created sketches:35
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 11

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 36b9e4c055f32718a036cabaf767325b010c7485
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training_generator.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/integration_tests/test_image_data_tasks.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training_generator.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [43, 44, 51, 64, 66]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 43
✓
Start transforming line: 44
x Fail! Line: 44 could not be transformed: 'not is_sequence and use_multiprocessing and workers > 1'
Start transforming line: 51
✓
Start transforming line: 64
x Fail! Line: 64 could not be transformed: '   isinstance(validation_data, Sequence))'
Start transforming line: 66
x Fail! Line: 66 could not be transformed: 'not validation_steps)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 14 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[44, 64, 66]
✓ Number of created sketches:14
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 12

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 13

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 2bfd1f2c950df5fc3f40b903c1966f1b0a48bee4
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training_generator.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/engine/test_training.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training_generator.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [127]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 127
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 5 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:5
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 14

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 98465b85d020f1326bcef7632f1261a9a7a84e92
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/metrics.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/metrics_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/metrics.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [48]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 48
x Fail! Line: 48 could not be transformed: 'return K.mean(K.in_top_k(y_pred, K.cast(K.max(y_true, axis=-1), 'int32'), k),'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[48]
✓ Number of created sketches:0
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 15

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 5b6243485acc20cc36f2db4f258512c332d691ec
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/callbacks.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/test_callbacks.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/callbacks.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [1125, 1133, 1135, 1161]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 1125
x Fail! Line: 1125 could not be transformed: 'self.file_flags = 'b' six.PY2 and os.name == 'nt' '''
Start transforming line: 1133
✓
Start transforming line: 1135
✓
Start transforming line: 1161
x Fail! Line: 1161 could not be transformed: ' fieldnames=['epoch'] + self.keys, dialect=CustomDialect)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 79 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[1125, 1161]
✓ Number of created sketches:79
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 16

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 514aca20c6f076a86819d7180f36c3b2e8bcc33b
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/sequential.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/test_sequential_model.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/sequential.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [222, 223, 274, 276, 281]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 222
✓
Start transforming line: 223
✓
Start transforming line: 274
✓
Start transforming line: 276
x Fail! Line: 276 could not be transformed: 'config.append({'
Start transforming line: 281
x Fail! Line: 281 could not be transformed: ''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 111 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[276, 281]
✓ Number of created sketches:111
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 17

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: c913b6da92f6ab9a3f4c897caa4085e782a14680
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/metrics.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/metrics_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/metrics.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [37]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 37
x Fail! Line: 37 could not be transformed: 'return K.cast(K.equal(K.max(y_true, axis=-1),'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[37]
✓ Number of created sketches:0
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 18

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 9400be98783135a1d42dd238f4e6c3aa048eceea
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/backend/backend_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [2548, 2646]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 2548
✓
Start transforming line: 2646
x Fail! Line: 2646 could not be transformed: 'fetched = self._callable_fn(*array_vals)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 2 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[2646]
✓ Number of created sketches:2
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 19

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: f9210387088fe91b5bc8999cf0cb41a0fe9eacf6
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/cntk_backend.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/layers/recurrent_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/cntk_backend.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [61, 74, 75, 76, 1442]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 61
x Fail! Line: 61 could not be transformed: 'return _LEARNING_PHASE _LEARNING_PHASE in {0, 1} _LEARNING_PHASE_PLACEHOLDER'
Start transforming line: 74
x Fail! Line: 74 could not be transformed: '"""Reset learning phase flag cntk backend.'
Start transforming line: 75
x Fail! Line: 75 could not be transformed: '"""'
Start transforming line: 76
x Fail! Line: 76 could not be transformed: 'global _LEARNING_PHASE'
Start transforming line: 1442
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 4 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[61, 74, 75, 76]
✓ Number of created sketches:4
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 20

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 76da5f0a21ca98e4bf6706e182fb825243e76204
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/cntk_backend.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/layers/convolutional_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/cntk_backend.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [2189, 2211, 3452, 3589, 3613]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 2189
x Fail! Line: 2189 could not be transformed: ' padding='valid', data_format=None)'
Start transforming line: 2211
x Fail! Line: 2211 could not be transformed: 'output_shape=output_shape)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[2189, 2211]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 21

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: c7b7328cc99fd5d7c298e57c6020043451d89a61
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/callbacks.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/test_callbacks.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/callbacks.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [488]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 488
x Fail! Line: 488 could not be transformed: ' baseline=None)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[488]
✓ Number of created sketches:0
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 22

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 23

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 3dcd9c767ce6875fc8b69c74971ac8a552e23131
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/sequential.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/test_sequential_model.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/sequential.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [152, 153]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 152
✓
Start transforming line: 153
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 41 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:41
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 24

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: d7884570b10951d156aa086ee29a4df9eab79cf3
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/callbacks.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/test_callbacks.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/callbacks.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [789, 790]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 789
x Fail! Line: 789 could not be transformed: 'tf.summary.histogram('{}_out'.format(layer.name),'
Start transforming line: 790
x Fail! Line: 790 could not be transformed: ' layer.output)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[789, 790]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 25

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 26

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 87417470c8168772559be0531e297120c569a422
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/backend/backend_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [2874]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 2874
x Fail! Line: 2874 could not be transformed: 'new_states = [tf.where(tiled_mask_t, new_states[i], states[i]) i in range(len(states))]'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[2874]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 27

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 28

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 6171b3656ebd9b6038f709ba83f7475de284ba4e
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/preprocessing/sequence.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/preprocessing/sequence_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/preprocessing/sequence.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [332, 344, 348]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 332
x Fail! Line: 332 could not be transformed: '(self.batch_size * self.stride)))'
Start transforming line: 344
x Fail! Line: 344 could not be transformed: 'self.start_index, self.end_index, size=self.batch_size)'
Start transforming line: 348
x Fail! Line: 348 could not be transformed: 'self.stride, self.end_index), self.stride)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[332, 344, 348]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 29

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: a341c014412cbfc86a9dd9816ae228e398dff3a2
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/metrics_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [1177, 1178, 1179, 1366, 1367]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 1177
✓
Start transforming line: 1178
✓
Start transforming line: 1179
x Fail! Line: 1179 could not be transformed: 'm.reset_states()'
Start transforming line: 1366
✓
Start transforming line: 1367
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 54809 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[1179]
✓ Number of created sketches:54809
Time needed: 28.85 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 30

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: c08ef613af27da896cee168daeee5c6fad1980b6
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/engine/test_training.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [2215, 2402]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 2215
✓
Start transforming line: 2402
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 19 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:19
Time needed: 0.39 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 31

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: ced81968b0e9d8b1389e6580721ac60d9cf3ca60
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/backend/backend_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [3945, 3946]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 3945
✓
Start transforming line: 3946
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 19 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:19
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 32

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: a3d160b9467c99cbb27f9aa0382c759f45c8ee66
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/callbacks.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/test_callbacks.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/callbacks.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [901, 909, 918, 939, 942]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 901
x Fail! Line: 901 could not be transformed: 'epsilon threshold measuring the new optimum,'
Start transforming line: 909
x Fail! Line: 909 could not be transformed: ' verbose=0, mode='auto', epsilon=1e-4, cooldown=0, min_lr=0)'
Start transforming line: 918
✓
Start transforming line: 939
x Fail! Line: 939 could not be transformed: 'self.monitor_op = lambda a, b np.less(a, b - self.epsilon)'
Start transforming line: 942
x Fail! Line: 942 could not be transformed: 'self.monitor_op = lambda a, b np.greater(a, b + self.epsilon)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 10 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[901, 909, 939, 942]
✓ Number of created sketches:10
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 33

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 1c9a49781da2101507db23e2014e4e5d16bd2e52
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/preprocessing/text.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/preprocessing/text_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/preprocessing/text.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [41, 42, 44, 56]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 41
✓
Start transforming line: 42
x Fail! Line: 42 could not be transformed: 'translate_map = dict((ord(c), unicode(split)) c in filters)'
Start transforming line: 44
✓
Start transforming line: 56
x Fail! Line: 56 could not be transformed: ''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 209 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[42, 56]
✓ Number of created sketches:209
Time needed: 0.04 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 34

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 7ef5244a2f1f7f7b76e3c804b82cbb20cdf4d139
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/test_multiprocessing.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [2165, 2197, 2369, 2493]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 2165
✓
Start transforming line: 2197
✓
Start transforming line: 2369
✓
Start transforming line: 2493
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 399 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:399
Time needed: 0.05 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 35

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 06eaeebecfb73c23bfd531013ca172ee3bf5069c
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/preprocessing/image.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/preprocessing/image_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/preprocessing/image.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [583, 584, 1230]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 583
✓
Start transforming line: 584
✓
Start transforming line: 1230
x Fail! Line: 1230 could not be transformed: '   target_size=self.target_size,'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 8 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[1230]
✓ Number of created sketches:8
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 36

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 85f011df5a5c0fcf1f01b39eca338eb6b7e58401
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/layers/convolutional_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/backend/tensorflow_backend.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [3419, 3422]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 3419
✓
Start transforming line: 3422
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 155 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:155
Time needed: 0.03 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 37

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 81f6b3aa5b2b6215a533180e848a3b4dff851d03
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/layers/recurrent.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/layers/wrappers_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/layers/recurrent.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [324, 325, 521, 523, 527]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 324
x Fail! Line: 324 could not be transformed: 'class MinimalRNNCell(keras.layers.Layer)'
Start transforming line: 325
x Fail! Line: 325 could not be transformed: ''
Start transforming line: 521
✓
Start transforming line: 523
✓
Start transforming line: 527
x Fail! Line: 527 could not be transformed: ''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 114 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[324, 325, 527]
✓ Number of created sketches:114
Time needed: 0.05 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 38

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 53ec990d54130dd0a457dd235c93d39de32d571d
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/layers/recurrent.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/layers/recurrent_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/layers/recurrent.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [109]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 109
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 7 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:7
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 39

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 3a431ea52d090fb3ef8a1e0e5d7f796d9a42e097
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/utils/generic_utils.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/utils/generic_utils_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/utils/generic_utils.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [330]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 330
x Fail! Line: 330 could not be transformed: 'current < self.target)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[330]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 40

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 871007dbb0e6211459b9d16244cc3c9683459df7
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/layers/recurrent.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/layers/recurrent_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/layers/recurrent.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [398, 400, 408]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 398
✓
Start transforming line: 400
x Fail! Line: 400 could not be transformed: 'output_dim = self.cell.state_size'
Start transforming line: 408
x Fail! Line: 408 could not be transformed: 'state_shape = [(input_shape[0], output_dim) _ in self.states]'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 3 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[400, 408]
✓ Number of created sketches:3
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 41

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: a27b4a51f4880ad3a7669531b667c1ef44b173ef
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/utils/data_utils.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/utils/data_utils_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/utils/data_utils.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [556, 634, 639, 642, 655]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 556
✓
Start transforming line: 634
✓
Start transforming line: 639
x Fail! Line: 639 could not be transformed: 'except Exception'
Start transforming line: 642
x Fail! Line: 642 could not be transformed: ''
Start transforming line: 655
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 104 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[639, 642]
✓ Number of created sketches:104
Time needed: 0.03 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 42

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: 67a432c273cbd65866b1d2cb1e2c62714b633b6e
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/engine/test_training.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/engine/training.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [1903, 1944, 2014, 2030, 2031]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 1903
x Fail! Line: 1903 could not be transformed: '  steps_per_epoch,'
Start transforming line: 1944
x Fail! Line: 1944 could not be transformed: 'divided by the batch size. Not used using `Sequence`.'
Start transforming line: 2014
x Fail! Line: 2014 could not be transformed: 'raise ValueError('When using a generator validation data, ''
Start transforming line: 2030
✓
Start transforming line: 2031
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 77 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[1903, 1944, 2014]
✓ Number of created sketches:77
Time needed: 0.05 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 43

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 44

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 45

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
GIT RESET TO: d368dc870bfd8fdd4ca0ff82bd5b61aa549291c5
bug_file = /Users/daniel/Bachelorarbeit/Projects/keras/keras/layers/recurrent.py
bug_test_file = /Users/daniel/Bachelorarbeit/Projects/keras/tests/keras/layers/recurrent_test.py
TEST EXECUTION:
x FAIL! Test fails or has errors.
✓ PySketchFix is started...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/Bachelorarbeit/Projects/keras/keras/layers/recurrent.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [1806, 1807, 1808, 1809]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 1806
✓
Start transforming line: 1807
✓
Start transforming line: 1808
✓
Start transforming line: 1809
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 20448 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:20448
Time needed: 2.62 minutes.
#######################################################################################################
Results with bug numbers:
Project:keras
Failing:[1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 45]
Passing:[]
Empty Suspicious Lines:[2, 12, 22, 25, 27, 43, 44]
No bug information is found:[]
